### ISSUE TITLE
REST endpoint generator improvements

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-FluxC-Android#128]
- [x] <s>Support endpoints of type `/sites/$site/posts/slug:$post_slug`</s> (addressed in #217)
- [x] <s>Fix stripping of `_id` from `/read/feed/$feed_url_or_id` (or create a new rule that catches this case) ref: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/126#issuecomment-240675471</s> (addressed in #383)
- [x] <s>Allow setting types when defining endpoints in the text file, e.g. the above endpoint should create two methods:</s> (addressed in #181)
    ```
    /read/feed/$feed_url_or_id#long, /read/feed/$feed_url_or_id#String
    ```

**Comment by aforcier** [comment]
All of the improvements have been added!
