### ISSUE TITLE
Resolve/Suppress Detekt Baseline Warnings - FluxC Module

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-FluxC-Android#2485]
Parent #2479

This issue is about resolving/suppressing the Detekt related warnings that are within Detekt's [baseline](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/config/detekt/baseline.xml) for the `fluxc` module.

Number of Warnings: `283`

### Tasks

- [x] Resolve/Suppress `style` related warnings. @ParaskP7 #2490
    - style (`132`) ✅
        1. DataClassShouldBeImmutable (`70`) ✅
        2. ExplicitItLambdaParameter (`1`) ✅
        3. ForbiddenComment (`10`) ✅
        4. MagicNumber (`18`) ✅
        5. MaxLineLength (`15`) ✅
        6. ReturnCount (`10`) ✅
        7. UnnecessaryAbstractClass (`1`) ✅
        8. UnusedPrivateMember (`4`) ✅
        9. UseCheckOrError (`1`) ✅
        10. UtilityClassWithPublicConstructor (`2`) ✅
- [x] Resolve/Suppress `complexity/naming` related warnings. @ParaskP7 #2491 (with [comment](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2491#discussion_r943548751), cc @irfano)
    - complexity (`59`) ✅
        1. ComplexCondition (`6`) ✅
        2. ComplexMethod (`14`) ✅
        3. LargeClass (`4`) ✅
        4. LongMethod (`6`) ✅
        5. LongParameterList (`21`) ✅
        6. NestedBlockDepth (`8`) ✅
    - naming (`51`) ✅
        1. ConstructorParameterNaming (`31`) ✅
        2. VariableNaming (`20`) ✅
- [x] Resolve/Suppress `coroutines/empty-blocks/exceptions/performance/potential-bugs` related warnings. @ParaskP7 #2493
    - coroutines (`2`) ✅
        1. GlobalCoroutineUsage (`2`) ✅ (with [comment](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1605#issuecomment-1210609730), cc @khaykov @develric) 
    - empty-blocks (`1`) ✅
        1. EmptyFunctionBlock (`1`) ✅
    - exceptions (`33`) ✅
        1. SwallowedException (`23`) ✅
        2. TooGenericExceptionCaught (`8`) ✅
        3. TooGenericExceptionThrown (`2`) ✅
    - performance (`4`) ✅
        1. SpreadOperator (`4`) ✅
    - potential-bugs (`1`) ✅
        1. ImplicitDefaultLocale (`1`) ✅
