### ISSUE TITLE
Resolve/Suppress Detekt Baseline Warnings - Plugins Woo Commerce Module

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-FluxC-Android#2486]
Parent #2479

This issue is about resolving/suppressing the Detekt related warnings that are within Detekt's [baseline](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/config/detekt/baseline.xml) for the `plugins:woocommerce` module.

Number of Warnings: `200`

### Tasks

- [x] Resolve/Suppress `style` related warnings. @ParaskP7 #2494
    - style (`52`) ✅
        1. DataClassShouldBeImmutable (`3`) ✅
        3. ForbiddenComment (`6`) ✅
        4. MagicNumber (`15`) ✅ (with [comment](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1103#issuecomment-1211868401), cc @anitaa1990 @AmandaRiu )
        5. MaxLineLength (`9`) ✅
        6. ReturnCount (`13`) ✅
        7. SpacingBetweenPackageAndImports (`1`) ✅
        8. UnnecessaryAbstractClass (`2`) ✅
        9. UnusedPrivateMember (`1`) ✅
        10. UseCheckOrError (`2`) ✅
- [x] Resolve/Suppress `complexity/naming` related warnings. @ParaskP7 #2498
    - complexity (`37`) ✅
        1. ComplexCondition (`1`) ✅
        2. ComplexMethod (`10`) ✅
        3. LargeClass (`4`) ✅
        4. LongMethod (`10`) ✅
        5. LongParameterList (`6`) ✅
        6. NestedBlockDepth (`6`) ✅
    - naming (`99`) ✅
        1. ConstructorParameterNaming (`9`) ✅
        2. MemberNameEqualsClassName (`1`) ✅
        3. VariableNaming (`89`) ✅
- [x] Resolve/Suppress `coroutines/empty-blocks/exceptions/performance/potential-bugs` related warnings. @ParaskP7 #2506
    - empty-blocks (`1`) ✅
        1. EmptyFunctionBlock (`1`) ✅
    - exceptions (`4`) ✅
        1. SwallowedException (`2`) ✅
        2. TooGenericExceptionCaught (`2`) ✅
    - performance (`6`) ✅
        1. ArrayPrimitive (`2`) ✅
        2. SpreadOperator (`4`) ✅
    - potential-bugs (`1`) ✅
        1. ImplicitDefaultLocale (`1`) ✅
