### ISSUE TITLE
Resolve/Suppress Detekt Baseline Warnings - Example Module

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-FluxC-Android#2487]
Parent #2479

This issue is about resolving/suppressing the Detekt related warnings that are within Detekt's [baseline](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/config/detekt/baseline.xml) for the `example` module.

Number of Warnings: `176`

### Tasks

- [x] Resolve/Suppress `style` related warnings. @ParaskP7 #2502
    - style (`87`) ✅
        1. DataClassShouldBeImmutable (`4`) ✅
        4. MagicNumber (`6`) ✅
        5. MaxLineLength (`3`) ✅
        6. ReturnCount (`2`) ✅
        7. UnnecessaryAbstractClass (`3`) ✅
        8. UnusedPrivateMember (`11`) ✅
        9. UseArrayLiteralsInAnnotations (`1`) ✅
        10. UseCheckOrError (`6`) ✅
        11. UtilityClassWithPublicConstructor (`1`) ✅
        12. WildcardImport (`49`) ✅
- [x] Resolve/Suppress `complexity/naming` related warnings. @ParaskP7 #2504
    - complexity (`63`) ✅
        1. ComplexCondition (`2`) ✅
        2. ComplexMethod (`16`) ✅
        3. LargeClass (`7`) ✅
        4. LongMethod (`36`) ✅
        6. NestedBlockDepth (`2`) ✅
    - naming (`1`) ✅
        1. TopLevelPropertyNaming (`1`) ✅
- [x] Resolve/Suppress `coroutines/empty-blocks/exceptions/performance/potential-bugs` related warnings. @ParaskP7 #2507
    - coroutines (`9`) ✅
        1. GlobalCoroutineUsage (`9`) ✅
    - empty-blocks (`3`) ✅
        1. EmptyFunctionBlock (`3`) ✅
    - exceptions (`13`) ⚙️
        1. PrintStackTrace (`2`) ✅
        2. SwallowedException (`2`) ✅
        3. TooGenericExceptionCaught (`9`) ✅
    - performance (`1`) ✅
        1. SpreadOperator (`1`) ✅
