### ISSUE TITLE
Upgrade FluxC-Android to Android 13

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-FluxC-Android#2623]
The library will be upgraded to Android 13.

### Tasks

- [x] Upgrade `compileSdk` to 33 https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2674
- [x] Upgrade `targetSdk` to 33 https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2685
- [x] Publish a new version: [v2.21.0](https://github.com/wordpress-mobile/WordPress-FluxC-Android/releases/tag/2.21.0)
- [x] Bump FluxC version on WPAndroid repo:
- [x] Bump FluxC version on Login-Flow library
- [ ] Bump FluxC version on [WooCommerce-Android repo](https://github.com/woocommerce/woocommerce-android/blob/trunk/build.gradle)?:

**Comment by ravishanker** [comment]
PR for compileSdkVersion https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2674

**Comment by ravishanker** [comment]
PR for targetSdkVersion update https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2685

**Comment by ravishanker** [comment]
Let Woo Mobile update to the latest in their own Android 13 update
