### ISSUE TITLE
Nullability Annotations to Java Classes - Client & Response

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-FluxC-Android#2798]
Parent #2795

This issue is about adding missing nullability annotations (`@Nullable` & `@NonNull`) to as many Java-related `RestClient` & `Response` classes as possible, including fields, arguments, parameters, and return values.

PS: The main focus is on Java-related `RestClient` & `Response` classes. Another issue will cover other more foundational aspects of the `network` package (see #2853).

-----

```[tasklist]
### Tasks (`Base`)
- [ ] [BaseWPAPIRestClient.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/BaseWPAPIRestClient.java#L4)
- [ ] [BaseWPOrgAPIClient.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/wporg/BaseWPOrgAPIClient.java#L4)
- [ ] [BaseXMLRPCClient.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/BaseXMLRPCClient.java#L4)
```

-----

## BaseWPAPIRestClient

```[tasklist]
### Tasks (`discovery`)
- [ ] #2872
```

```[tasklist]
### Tasks (`rest/wpcom`)
- [ ] [AccountRestClient.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/72527be57db5c63fff17e053f5919970e0011961/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AccountRestClient.java#L4)
- [ ] #2868
- [ ] #2878
- [ ] [PluginRestClient.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/72527be57db5c63fff17e053f5919970e0011961/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/plugin/PluginRestClient.java#L4)
- [ ] [PostRestClient.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/72527be57db5c63fff17e053f5919970e0011961/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/post/PostRestClient.java#L4)
- [ ] [ReaderRestClient.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/72527be57db5c63fff17e053f5919970e0011961/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/reader/ReaderRestClient.java#L4)
- [ ] #2826
- [ ] #2893
```

-----

## BaseWPOrgAPIClient

```[tasklist]
### Tasks (`wporg/plugin`)
- [ ] [PluginWPOrgClient.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/wporg/plugin/PluginWPOrgClient.java#L4)
```

-----

## BaseXMLRPCClient

```[tasklist]
### Tasks (`discovery`)
- [ ] #2872
```

```[tasklist]
### Tasks (`xmlrpc`)
- [ ] #2868
- [ ] #2878
- [ ] [PostXMLRPCClient.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/72527be57db5c63fff17e053f5919970e0011961/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/post/PostXMLRPCClient.java#L4)
- [ ] #2866
```
