### ISSUE TITLE
Nullability Annotations to Java Classes - Store

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-FluxC-Android#2800]
Parent #2795

This issue is about adding missing nullability annotations (`@Nullable` & `@NonNull`) to as many Java-related `Store` classes as possible, including fields, arguments, parameters, and return values.

-----

```[tasklist]
### Tasks (`Base`)
- [ ] #2846
```

-----

```[tasklist]
### Tasks (`Implementations`)
- [ ] [AccountStore.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/store/AccountStore.java#L4)
- [ ] [CommentStore.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/store/CommentStore.java#L4)
- [ ] [MediaStore.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/store/MediaStore.java#L4)
- [ ] [PluginStore.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginStore.java#L4)
- [ ] [PostStore.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/store/PostStore.java#L4)
- [ ] [ReaderStore.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/store/ReaderStore.java#L4)
- [ ] [TaxonomyStore.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/store/TaxonomyStore.java#L4)
- [ ] [ThemeStore.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/store/ThemeStore.java#L4)
- [ ] [UploadStore.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/store/UploadStore.java#L4)
```
