### ISSUE TITLE
Nullability Annotations to Java Classes - Utils

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-FluxC-Android#2801]
Parent #2795

This issue is about adding missing nullability annotations (`@Nullable` & `@NonNull`) to as many Java-related `Utils` classes as possible, including fields, arguments, parameters, and return values.

-----

```[tasklist]
### Tasks (`Main`)
- [ ] [MediaUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/d11aef788db3ec11a03359b1b198ffbb553b05f4/fluxc/src/main/java/org/wordpress/android/fluxc/utils/MediaUtils.java#L17)
- [ ] [ObjectsUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/utils/ObjectsUtils.java#L4)
- [ ] [SiteUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/d11aef788db3ec11a03359b1b198ffbb553b05f4/fluxc/src/main/java/org/wordpress/android/fluxc/utils/SiteUtils.java#L19)
- [ ] [WPUrlUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/utils/WPUrlUtils.java#L4)
```

```[tasklist]
### Tasks (`Error`)
- [ ] [CommentErrorUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/utils/CommentErrorUtils.java#L4)
- [ ] [ErrorUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/utils/ErrorUtils.java#L4)
- [ ] [SiteErrorUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/utils/SiteErrorUtils.java#L4)
```

```[tasklist]
### Tasks (`Example App`)
- [ ] [LogUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/example/src/main/java/org/wordpress/android/fluxc/example/LogUtils.java#L4)
```
