### ISSUE TITLE
Nullability Annotations to Java Classes - Network

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-FluxC-Android#2853]
Parent #2795

This issue is about adding missing nullability annotations (`@Nullable` & `@NonNull`) to as many Java-related `Network` classes as possible, including fields, arguments, parameters, and return values.

-----

```[tasklist]
### Tasks (`discovery`)
- [ ] [DiscoveryRequest.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/DiscoveryRequest.java#L4)
- [ ] [DiscoveryUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/DiscoveryUtils.java#L4)
- [ ] [DiscoveryXMLRPCRequest.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/DiscoveryXMLRPCRequest.java#L4)
- [ ] [SelfHostedEndpointFinder.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/SelfHostedEndpointFinder.java#L4)
- [ ] [WPAPIHeadRequest.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/discovery/WPAPIHeadRequest.java#L4)
```

```[tasklist]
### Tasks (`rest/wpapi`)
- [ ] [WPAPIGsonRequest.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/WPAPIGsonRequest.java#L4)
```

```[tasklist]
### Tasks (`rest/wpcom`)
- [ ] [WPComGsonRequest.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/WPComGsonRequest.java#L4)
- [ ] [GsonRequest.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/GsonRequest.java#L4)
- [ ] [JsonObjectOrEmptyArrayDeserializer.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/JsonObjectOrEmptyArrayDeserializer.java#L4)
- [ ] [JsonObjectOrFalseDeserializer.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/JsonObjectOrFalseDeserializer.java#L4)
```

```[tasklist]
### Tasks (`wporg`)
- [ ] [WPOrgAPIGsonRequest.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/wporg/WPOrgAPIGsonRequest.java#L4)
```

```[tasklist]
### Tasks (`xmlrpc`)
- [ ] [XMLRPCException.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLRPCException.java#L4)
- [ ] [XMLRPCFault.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLRPCFault.java#L4)
- [ ] [XMLRPCRequest.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLRPCRequest.java#L4)
- [ ] [XMLRPCSerializer.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLRPCSerializer.java#L4)
- [ ] [XMLRPCUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLRPCUtils.java#L4)
- [ ] [XMLSerializerUtils.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/xmlrpc/XMLSerializerUtils.java#L4)
```

```[tasklist]
### Tasks (`request`)
- [ ] [BaseRequest.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/BaseRequest.java#L4)
- [ ] [BaseRequestFuture.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/BaseRequestFuture.java#L4)
- [ ] [BaseUploadRequestBody.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/BaseUploadRequestBody.java#L4)
```

```[tasklist]
### Tasks (`http`)
- [ ] [HTTPAuthManager.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/HTTPAuthManager.java#L4)
- [ ] [HTTPAuthModel.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/HTTPAuthModel.java#L4)
- [ ] [OkHttpStack.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/OkHttpStack.java#L4)
```

```[tasklist]
### Tasks (`manager`)
- [ ] [MemorizingTrustManager.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/MemorizingTrustManager.java#L4)
- [ ] [OpenJdkCookieManager.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/OpenJdkCookieManager.java#L4)
```

```[tasklist]
### Tasks (`other`)
- [ ] [RetryOnRedirectBasicNetwork.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/RetryOnRedirectBasicNetwork.java#L4)
- [ ] [UserAgent.java](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/9f10cf5d25c241cff1d34a9a091e7439e7fca6ff/fluxc/src/main/java/org/wordpress/android/fluxc/network/UserAgent.java#L4)
```
