### ISSUE TITLE
Checklist before wpandroid integration

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-FluxC-Android#4]
- [x] Fully featured account store
- [x] Login tests with SSL + letsencrypt
- [x] Login tests with SSL self signed https://github.com/wordpress-mobile/WordPress-Stores-Android/issues/13
- [x] Login tests with HTTP Auth
- [x] Signout action https://github.com/wordpress-mobile/WordPress-Stores-Android/issues/25
- [x] Login tests with HTTP redirects
- [x] Login tests with HTTP -> HTTPS redirects
- [x] Tests with incorrect XML (PHP warnings)
- [x] Support HTTP Auth
- [x] Support Self Signed SSL
- [x] Support SNI
- [x] Support 2FA on wordpress.com
- [x] Test DB migration from wpstores version N to wpstores version N + 1 https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/180
- [x] Better network error handling
- [x] XMLRPC endpoint discover (we can reuse wpandroid code)
- [x] AccountStore: validate and create new user https://github.com/wordpress-mobile/WordPress-Stores-Android/issues/29
- [x] SiteStore: validate and create new site: https://github.com/wordpress-mobile/WordPress-Stores-Android/issues/30
