### ISSUE TITLE
Plugin Directory Checklist

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-FluxC-Android#690]
- [ ] Check if we can make any improvements to the API to fix the inconsistencies/issues
- [ ] Optimize DB queries #682
- [ ] Use DB query for `PluginSqlUtils.getLastRequestedPageForDirectoryType`
- [ ] Better error handling (check if we there are any specific errors we can handle)
- [x] Handle unexpected parse errors #683
- [ ] Add more connected tests for fetch plugin directory and search plugin directory, especially for specific error types if we can find it
- [ ] Add unit tests for plugin directory sql methods
- [ ] Make sure the last page is correctly handled especially for searches
- [ ] Support featured plugins #696

**Comment by oguzkocer** [comment]
> Check if we can make any improvements to the API to fix the inconsistencies/issues

We were able to achieve everything we have wanted with the current API. We'd still prefer to make some improvements but getting that to happen is not something on our plate right now.

> Optimize DB queries #682

See [this comment](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/682#issuecomment-365389371)

> Use DB query for `PluginSqlUtils.getLastRequestedPageForDirectoryType`

Moved to #682 

> Better error handling (check if we there are any specific errors we can handle)

We have integrated the feature into WPAndroid and haven't come across any new error types yet. I'll keep a close eye on this, but won't be looking for it specifically.

> Add more connected tests for fetch plugin directory and search plugin directory, especially for specific error types if we can find it

Looks like we have covered all the major cases, this item was more of a reminder to check the tests than anything else. We'll add new tests if we come across any issues (while fixing a bug or something).

> Add unit tests for plugin directory sql methods

PR incoming

> Make sure the last page is correctly handled especially for searches

We are using a single page in WPAndroid (even though FluxC allows pagination) and from my tests, the code seems to be handling the pagination just fine. We don't need to spend any more time on this right now.

> Support featured plugins #696 

This will be handled separately after the feature is merged into develop in WPAndroid.
